In [17]:
# 1. Carga de bibliotecas e base de dados
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/Gradua%C3%A7%C3%A3o/dados/pib.csv")

In [18]:
# 2. Análise Exploratória
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03
2,3,mar/04,110.43,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70
3,4,abr/04,106.77,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,148.92
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,151.68,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92

In [19]:
# 3. Separação de Treino e Teste
# Geração de amostra em uma série temporal (falaremos mais sobre isto adiante)
# através de uma janela temporal
treino = df.iloc[0:124]
teste  = df.iloc[125:137]

In [20]:
# 4. Construção das variáveis para regressão linear

# TREINO
# Variável X - localizamos a variável BRP na 4a posição indicial 
# Exercício: experimentar com diferentes variáveis e diferentes combinações de variáveis, avaliando o resultado do modelo preditivo

X_treino = treino.loc[:,['PIBi1', 'PIBi2']]

# Variável Y - PIB
Y_treino = treino.iloc[:,[2]]

In [21]:
# 5. Construção regressão
mod = LinearRegression()
mod.fit(X_treino,Y_treino)

LinearRegression()

In [22]:
# 6. Previsão em teste
X_teste = teste.loc[:,['PIBi1', 'PIBi2']]
Y_teste = teste.iloc[:,[2]]

Y_prev = mod.predict(X_teste)

In [1]:
# 7. Análise do Erro de Previsão
# Uso da métrica MSE
mse = mean_squared_error(Y_teste, Y_prev)

mse

NameError: ignored