<a href="https://colab.research.google.com/github/diogenesjusto/FIAP/blob/master/Gradua%C3%A7%C3%A3o/2024/20240402_ModeloAutoregressivo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Carga de bibliotecas
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as MAE

# Carga de dados
df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/SHIFT/Data/pib.csv")

# Separação de treino e teste
treino = df.iloc[0:126]
teste = df.iloc[126:138]

# Regressão
Y_treino = treino.iloc[:,[2]]
X = ['BRL', 'BRP'] # Regressão Linear Simples
# Modelo AutoRegressivo
#X = ['PIBi1', 'PIBi2']
X_treino = treino.loc[:,X]
mod = LinearRegression()
mod.fit(X_treino, Y_treino)
# Análise de coeficientes
print(mod.coef_)
print(mod.intercept_)

# Cálculo de erro com python
X_teste = teste.loc[:,X]
Y_prev = mod.predict(X_teste)
Y_real = teste.loc[:,['PIB']]
Erro = Y_prev - Y_real

# Erro de previsão
print(MAE(Y_real, Y_prev))

[[0.24600183 0.58872335]]
[18.69399402]
2.5719315349868026

In [4]:
# Como construir colunas com lag
df['PIBi1_'] = df['PIB'].shift(1)
df['PIBi2_'] = df['PIB'].shift(2)

df.head(15)

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12,PIBi1_,PIBi2_
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00,NaN,NaN
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,103.09,NaN
2,3,mar/04,110.43,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,102.05,103.09
3,4,abr/04,106.77,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,110.43,102.05
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,106.77,110.43
5,6,jun/04,109.19,89.25,119.93,96.11,87.79,128.51,96.83,84.00,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,108.08,106.77
6,7,jul/04,111.95,100.39,125.64,106.03,100.22,135.26,108.01,98.32,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,109.19,108.08
7,8,ago/04,110.92,94.20,129.67,102.13,93.66,139.38,103.81,87.53,...,110.43,102.05,103.09,103.91,104.10,106.27,104.52,102.59,111.95,109.19
8,9,set/04,110.18,95.54,126.70,102.50,94.93,138.84,104.68,91.66,...,106.77,110.43,102.05,103.09,103.91,104.10,106.27,104.52,110.92,111.95
9,10,out/04,109.71,99.46,124.85,105.14,98.58,136.18,106.93,93.66,...,108.08,106.77,110.43,102.05,103.09,103.91,104.10,106.27,110.18,110.92
10,11,nov/04,109.24,96.88,122.26,102.55,96.49,134.13,104.85,91.18,...,109.19,108.08,106.77,110.43,102.05,103.09,103.91,104.10,109.71,110.18
11,12,dez/04,111.53,114.60,124.11,116.72,112.92,134.31,117.67,120.85,...,111.95,109.19,108.08,106.77,110.43,102.05,103.09,103.91,109.24,109.71
12,13,jan/05,108.26,113.68,111.74,113.24,108.83,119.75,111.26,130.36,...,110.92,111.95,109.19,108.08,106.77,110.43,102.05,103.09,111.53,109.24
13,14,fev/05,105.52,96.36,107.86,98.93,93.41,116.18,98.47,99.42,...,110.18,110.92,111.95,109.19,108.08,106.77,110.43,102.05,108.26,111.53
14,15,mar/05,113.00,101.37,126.91,107.08,101.05,134.88,108.56,97.42,...,109.71,110.18,110.92,111.95,109.19,108.08,106.77,110.43,105.52,108.26

In [13]:
df2 = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/Gradua%C3%A7%C3%A3o/dados/desafio_baba.csv")

df2

,Unnamed: 0,X,date,mes,weekday,margem,venda,desconto,outdesc,outmg
0,1,1,20140801,agosto,sexta-feira,0.406111,110042.460,9190.907534,0,0
1,2,2,20140802,agosto,sabado,0.416022,58377.320,5713.043012,0,0
2,3,3,20140803,agosto,domingo,0.431993,64635.390,8621.708915,0,0
3,4,4,20140804,agosto,segunda-feira,0.409216,140417.321,18312.965640,0,0
4,5,5,20140805,agosto,terca-feira,0.449648,149700.286,19942.741300,0,0
...,...,...,...,...,...,...,...,...,...,...
391,392,392,20150827,agosto,quinta-feira,0.451562,NaN,5846.133551,0,0
392,393,393,20150828,agosto,sexta-feira,0.472608,NaN,2657.847261,0,0
393,394,394,20150829,agosto,sabado,0.385612,NaN,269.530000,0,0
394,395,395,20150830,agosto,domingo,0.495615,NaN,3434.838118,0,0
395,396,396,20150831,agosto,segunda-feira,0.391486,NaN,2122.636306,0,0